"""Subset the serif face (Noto Serif CJK SC, i.e. 思源宋体) to the characters this site uses.

Noto Serif CJK SC is Google's release of Source Han Serif under the SIL OFL with no Reserved Font Name,
so subsets may keep their names. The source OTFs are downloaded once into .cache/fonts/ (not committed).

Characters come from the UI code and the app data, cut into slices with their own unicode-range, so a page
only downloads the slices for the characters it shows. Slices are filled tier by tier so the first screen
needs few of them: the welcome page and tabs first, then place, segment and road names, then everything else.

Writes public/fonts/serif-<weight>-<n>.<hash>.woff2, src/fonts.css and src/data/font-charset.json
(the test in src/lib/fonts.test.ts fails when data gains characters that are not in the subset).
Re-run after changing data or UI text: python3 scripts/build_fonts.py
"""
import collections, glob, hashlib, json, os, re, shutil, urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont
from _common import path, UA

SRC = "https://github.com/notofonts/noto-cjk/raw/main/Serif"
WEIGHTS = {400: "Regular", 700: "Bold"}
SLICE = 250
FAMILY = "WL Serif"


def source(name):
    local = path(f".cache/fonts/{name}")
    if not os.path.exists(local):
        os.makedirs(os.path.dirname(local), exist_ok=True)
        url = f"{SRC}/SubsetOTF/SC/{name}" if name.endswith(".otf") else f"{SRC}/{name}"
        with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=300) as r, open(local, "wb") as f:
            shutil.copyfileobj(r, f)
    return local


def corpus():
    files = glob.glob(path("src/**/*.ts"), recursive=True) + glob.glob(path("src/**/*.tsx"), recursive=True) \
        + glob.glob(path("src/data/*.json")) + [path("index.html")]
    count = collections.Counter()
    for f in files:
        with open(f, encoding="utf-8") as fh:
            count.update(fh.read())
    return count


def tiers():
    """Characters of the first screen, then of names shown in the serif face everywhere."""
    def read(p):
        with open(path(p), encoding="utf-8") as fh:
            return fh.read()
    route = json.loads(read("src/data/route.json"))
    nodes = {n["id"]: n for n in route["nodes"]}
    welcome = read("src/components/Welcome.tsx")
    hero = re.findall(r'"(\w+)"', re.search(r"const HERO = \[(.*?)\]", welcome).group(1))
    first = welcome + read("src/App.tsx") + "".join(s["name"] + s["range"] for s in route["segs"]) \
        + "".join(nodes[i]["n"] + (nodes[i].get("img") or {}).get("title", "") for i in hero if i in nodes)
    names = "".join(n["n"] for n in route["nodes"]) + "".join(r["name"] for r in json.loads(read("src/data/roads.json")))
    return [set(first), set(names)]


def ranges(cps):
    cps = sorted(cps)
    out, start = [], cps[0]
    for a, b in zip(cps, cps[1:] + [None]):
        if b != a + 1:
            out.append(f"U+{start:X}" if start == a else f"U+{start:X}-{a:X}")
            start = b
    return ",".join(out)


def main():
    regular = source(f"NotoSerifSC-{WEIGHTS[400]}.otf")
    cmap = TTFont(regular, lazy=True).getBestCmap()
    count = corpus()
    # printable ASCII is always included so numbers and Latin in headings match the CJK glyphs
    chars = {chr(c) for c in range(0x20, 0x7F)} | {ch for ch in count if ord(ch) > 0x7F}
    missing = sorted((ch for ch in chars if ord(ch) not in cmap and ch.strip()), key=ord)
    chars = [ch for ch in chars if ord(ch) in cmap]
    slices, done = [], set()
    for tier in tiers() + [set(chars)]:
        part = sorted((ch for ch in chars if ch in tier and ch not in done), key=lambda ch: (-count[ch], ord(ch)))
        done.update(part)
        slices += [part[i:i + SLICE] for i in range(0, len(part), SLICE)]
    chars = [ch for part in slices for ch in part]

    out_dir = path("public/fonts")
    shutil.rmtree(out_dir, ignore_errors=True)
    os.makedirs(out_dir)
    shutil.copy(source("LICENSE"), os.path.join(out_dir, "OFL.txt"))
    css = [f"/* Generated by scripts/build_fonts.py: {FAMILY} = Noto Serif CJK SC (思源宋体), SIL OFL 1.1, see public/fonts/OFL.txt */"]
    total = 0
    for weight, name in WEIGHTS.items():
        src = source(f"NotoSerifSC-{name}.otf")
        for i, part in enumerate(slices):
            opts = subset.Options()
            opts.flavor = "woff2"
            opts.layout_features = ["*"]
            opts.name_IDs = ["*"]
            opts.notdef_outline = True
            font = subset.load_font(src, opts)
            sub = subset.Subsetter(opts)
            sub.populate(unicodes=[ord(ch) for ch in part])
            sub.subset(font)
            tmp = os.path.join(out_dir, "tmp.woff2")
            subset.save_font(font, tmp, opts)
            # the content hash in the name lets the files be cached for good
            with open(tmp, "rb") as fh:
                file = f"serif-{weight}-{i}.{hashlib.sha256(fh.read()).hexdigest()[:8]}.woff2"
            os.replace(tmp, os.path.join(out_dir, file))
            total += os.path.getsize(os.path.join(out_dir, file))
            css.append(f'@font-face {{ font-family: "{FAMILY}"; font-style: normal; font-weight: {weight}; font-display: swap; '
                       f'src: url("/fonts/{file}") format("woff2"); unicode-range: {ranges([ord(ch) for ch in part])}; }}')
    with open(path("src/fonts.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(css) + "\n")
    with open(path("src/data/font-charset.json"), "w", encoding="utf-8") as f:
        json.dump({"covered": "".join(sorted(chars, key=ord)), "notInFont": "".join(missing)}, f, ensure_ascii=False)
    print(f"{len(chars)} characters, {len(slices)} slices x {len(WEIGHTS)} weights, {total / 1024:.0f} KB in all;"
          f" not in the font: {''.join(missing) or 'none'}")


if __name__ == "__main__":
    main()
